import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href={"/"}>
        <h1>Hello</h1>
        </Link>
        <Link href={"/About"}>
        <h1>
          About
        </h1>
        </Link>
        {children}
        </body>
    </html>
  )
}
